# Generated by Django 3.2 on 2022-06-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineVoltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_voltage', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('friendly_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.IntegerField()),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('nearest_sub_number', models.CharField(max_length=10)),
                ('landowner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('landowner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('landowner_phone_number', models.IntegerField(blank=True, null=True)),
                ('permission', models.IntegerField(choices=[(0, 'Granted'), (1, 'Denied'), (2, 'N/A')], default=0)),
                ('work_description', models.TextField()),
                ('hours_to_complete', models.IntegerField()),
                ('number_of_crew_members', models.IntegerField()),
                ('switch_out_required', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('traffic_management_required', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('site_safety_hazards', models.TextField()),
                ('site_environmental_hazards', models.TextField()),
                ('work_completed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('line_voltage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.linevoltage')),
                ('surveyor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tools_required_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_1', to='logs.toolsrequired')),
                ('tools_required_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_2', to='logs.toolsrequired')),
                ('tools_required_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_3', to='logs.toolsrequired')),
                ('tools_required_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_4', to='logs.toolsrequired')),
                ('tools_required_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_5', to='logs.toolsrequired')),
                ('tools_required_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_6', to='logs.toolsrequired')),
                ('tools_required_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_7', to='logs.toolsrequired')),
                ('tools_required_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_required_8', to='logs.toolsrequired')),
                ('tree_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.treecategory')),
            ],
        ),
    ]
